[protoc]
version = "3.12.3"

exclude = [
  "tools",
]

[[plugins]]
name = "rust"
output = "../../satelit-import/src/proto"
options = "grpc,no-flat-modules"
path = "tools/bin/protoc-gen-rust"

[[plugins]]
name = "go"
output = "../../satelit-scraper/proto"
options = "plugins=grpc"
path = "tools/bin/protoc-gen-go"

[[plugins]]
name = "rust"
output = "../../satelit-scheduler/src/proto"
options = "grpc,no-flat-modules"
path = "tools/bin/protoc-gen-rust"
